# Algemene configuratie voor de syllabi, alles hier is overschrijfbaar via de
# _config.yml in een specifiek boek.

# author - dynamisch op basis van committers
# copyright - dynamisch op basis van laatste commit datum

html:
  favicon: "" # TODO
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  
  # baseurl - dynamisch op basis van titel en branch

sphinx:
  config:
    html_static_path: [ "../../../../theme/_static" ]
    templates_path: [ "../../../../theme/_templates" ]
    html_css_files: [ "custom.css" ]
    html_theme_options:
      navbar_start: [ "navbar_logo" ]
