name: Build syllabi

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # Cache alles in de workspace, zodat ook de checkout en build output
      # gecached wordt
      - uses: actions/cache@v4
        if: ${{ !contains(github.event.head_commit.message, '!nocache') }}
        with:
          path: ${{ github.workspace }}
          key: ${{ github.workflow_ref }}

      - uses: actions/checkout@v4
        with:
          # Checkout alle submodules
          submodules: true
          # Geen clean en reset, zodat we de _build output behouden
          clean: false
          # Fetch de gehele historie, zodat de auteurs functie werkt
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r requirements.txt

      - run: |
          python build.py

      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "_build"
      - uses: actions/deploy-pages@v4
        id: deployment
